###################################################################

# Created by write_sdc on Fri May 31 10:49:49 2019

###################################################################
set sdc_version 2.0

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_fanout 6 [current_design]
set_max_area 0
set_load -pin_load 1 [get_ports {data_out[7]}]
set_load -pin_load 1 [get_ports {data_out[6]}]
set_load -pin_load 1 [get_ports {data_out[5]}]
set_load -pin_load 1 [get_ports {data_out[4]}]
set_load -pin_load 1 [get_ports {data_out[3]}]
set_load -pin_load 1 [get_ports {data_out[2]}]
set_load -pin_load 1 [get_ports {data_out[1]}]
set_load -pin_load 1 [get_ports {data_out[0]}]
create_clock [get_ports clk]  -period 20  -waveform {0 10}
set_clock_latency 0.5  [get_clocks clk]
set_clock_uncertainty 0.1  [get_clocks clk]
set_input_delay -clock clk  -max 1  [get_ports clk]
set_input_delay -clock clk  -max 1  [get_ports rst_n]
set_input_delay -clock clk  -max 1  [get_ports {address[3]}]
set_input_delay -clock clk  -max 1  [get_ports {address[2]}]
set_input_delay -clock clk  -max 1  [get_ports {address[1]}]
set_input_delay -clock clk  -max 1  [get_ports {address[0]}]
set_input_delay -clock clk  -max 1  [get_ports {data_in[15]}]
set_input_delay -clock clk  -max 1  [get_ports {data_in[14]}]
set_input_delay -clock clk  -max 1  [get_ports {data_in[13]}]
set_input_delay -clock clk  -max 1  [get_ports {data_in[12]}]
set_input_delay -clock clk  -max 1  [get_ports {data_in[11]}]
set_input_delay -clock clk  -max 1  [get_ports {data_in[10]}]
set_input_delay -clock clk  -max 1  [get_ports {data_in[9]}]
set_input_delay -clock clk  -max 1  [get_ports {data_in[8]}]
set_input_delay -clock clk  -max 1  [get_ports {data_in[7]}]
set_input_delay -clock clk  -max 1  [get_ports {data_in[6]}]
set_input_delay -clock clk  -max 1  [get_ports {data_in[5]}]
set_input_delay -clock clk  -max 1  [get_ports {data_in[4]}]
set_input_delay -clock clk  -max 1  [get_ports {data_in[3]}]
set_input_delay -clock clk  -max 1  [get_ports {data_in[2]}]
set_input_delay -clock clk  -max 1  [get_ports {data_in[1]}]
set_input_delay -clock clk  -max 1  [get_ports {data_in[0]}]
set_output_delay -clock clk  -min 0.5  [get_ports {data_out[7]}]
set_output_delay -clock clk  -min 0.5  [get_ports {data_out[6]}]
set_output_delay -clock clk  -min 0.5  [get_ports {data_out[5]}]
set_output_delay -clock clk  -min 0.5  [get_ports {data_out[4]}]
set_output_delay -clock clk  -min 0.5  [get_ports {data_out[3]}]
set_output_delay -clock clk  -min 0.5  [get_ports {data_out[2]}]
set_output_delay -clock clk  -min 0.5  [get_ports {data_out[1]}]
set_output_delay -clock clk  -min 0.5  [get_ports {data_out[0]}]
set_drive 1  [get_ports clk]
set_drive 1  [get_ports rst_n]
set_drive 1  [get_ports {address[3]}]
set_drive 1  [get_ports {address[2]}]
set_drive 1  [get_ports {address[1]}]
set_drive 1  [get_ports {address[0]}]
set_drive 1  [get_ports {data_in[15]}]
set_drive 1  [get_ports {data_in[14]}]
set_drive 1  [get_ports {data_in[13]}]
set_drive 1  [get_ports {data_in[12]}]
set_drive 1  [get_ports {data_in[11]}]
set_drive 1  [get_ports {data_in[10]}]
set_drive 1  [get_ports {data_in[9]}]
set_drive 1  [get_ports {data_in[8]}]
set_drive 1  [get_ports {data_in[7]}]
set_drive 1  [get_ports {data_in[6]}]
set_drive 1  [get_ports {data_in[5]}]
set_drive 1  [get_ports {data_in[4]}]
set_drive 1  [get_ports {data_in[3]}]
set_drive 1  [get_ports {data_in[2]}]
set_drive 1  [get_ports {data_in[1]}]
set_drive 1  [get_ports {data_in[0]}]
